### ISSUE TITLE
Add option to change updating frequency

### ISSUE THREAD

**Issue by Luxtech** [f100024/syncthing_exporter#23]
Is it possible to make a option to change the polling rate?

When I run this exporter on my raspberry pi (thanks for making it compatible with arm!) the CPU usage of the Syncthing container spikes, see screenshot:
![image](https://user-images.githubusercontent.com/27952645/208250531-5fc08a7f-3e3b-4fb1-8d2a-25170679a014.png)

The interesting bit is that not the exporter container spikes but the Syncthing container itself.
I don't need accurate logs to the minute so if there was a option that I could set in the docker-compose file to log only once a hour for example that would be amazing!

**Comment by f100024** [comment]
@Luxtech 
Yes, you can update `scrape_interval` in the `Prometheus` configuration. It is usually set at the global level but can be overridden at the job level. [Link](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config).

Also, you can omit expensive requests to `syncthing` by skipping using [DB status report](https://docs.syncthing.net/rest/db-status-get.html) just don't use parameter `SYNCTHING_FOLDERSID`.

**Comment by f100024** [comment]
If you have questions please reopen issue.
