### ISSUE TITLE
Node reporting as down / failed if SyncThing usage reporting is off

### ISSUE THREAD

**Issue by d-rez** [f100024/syncthing_exporter#25]
Hey, firstly thanks for the exporter :) I'm still researching which metrics to use  but so far it mostly looks great!

I noticed that my node is being reported as "failed" using the example Grafana template, even though it's definitely UP and polling properly. 

The exact value reported for `syncthing_rest_svc_report_node_info` is:

```
# HELP syncthing_rest_svc_report_node_info Node's string information
# TYPE syncthing_rest_svc_report_node_info gauge
syncthing_rest_svc_report_node_info{longVersion="syncthing v1.24.0 \"Fermium Flea\" (go1.20.7 linux-amd64) root@buildkitsandbox 2023-09-05 12:36:23 UTC [noupgrade]",platform="linux-amd64",uniqueID="",version="v1.24.0"} 0
```

I did some digging and it appears that in https://github.com/f100024/syncthing_exporter/blob/7f940fdf3e59ad9ebaf9ce9d87b3589dc5049d2c/collector/rest_svc_report.go#L175C11-L175C11 the UniqueID has to be of non-zero length for the state to be set to 1.

The thing is... If I'm reading the [official syncthing config docs](https://docs.syncthing.net/users/config#config-option-options.uruniqueid) correctly, having syncthing stats reporting disabled from day zero means no UniqueID gets assigned. I have stats reporting disabled and can confirm the lack of UniqueID with:

```bash
# cat config.xml | grep Uniq
        <urUniqueID></urUniqueID>
```

My small suggestion would be to change this state to reflect something else than UniqueID. 

Thanks!

**Comment by f100024** [comment]
Hi @d-rez ,
thank you for your report. I fixed it in `0.3.6`, please check. :)
